using UnityEngine;

namespace LastLight.Presentation.Common
{
    /// <summary>
    /// One place for every colour and size in the UI.
    /// </summary>
    /// <remarks>
    /// The scene is generated by an editor tool, so the tool and the runtime views both need
    /// the same palette. Keeping it here rather than in the generator means a colour change is
    /// one edit that both sides pick up, and the values survive regenerating the scene.
    /// </remarks>
    public static class UiTheme
    {
        // Surfaces
        public static readonly Color Backdrop = new Color(0.055f, 0.063f, 0.094f, 1f);
        public static readonly Color Panel = new Color(0.114f, 0.129f, 0.180f, 0.94f);
        public static readonly Color PanelEdge = new Color(0.22f, 0.24f, 0.32f, 1f);
        public static readonly Color Overlay = new Color(0.02f, 0.02f, 0.04f, 0.88f);

        // Text
        public static readonly Color Ink = new Color(0.94f, 0.92f, 0.86f, 1f);
        public static readonly Color Muted = new Color(0.58f, 0.60f, 0.68f, 1f);

        // Resources
        public static readonly Color Light = new Color(1f, 0.78f, 0.36f, 1f);
        public static readonly Color Ward = new Color(0.46f, 0.72f, 1f, 1f);
        public static readonly Color Focus = new Color(1f, 0.86f, 0.42f, 1f);
        public static readonly Color Danger = new Color(0.90f, 0.34f, 0.30f, 1f);
        public static readonly Color Good = new Color(0.45f, 0.80f, 0.50f, 1f);

        // Card types
        public static readonly Color AttackCard = new Color(0.52f, 0.20f, 0.18f, 1f);
        public static readonly Color SkillCard = new Color(0.18f, 0.31f, 0.48f, 1f);
        public static readonly Color CardFace = new Color(0.16f, 0.17f, 0.22f, 1f);
        public static readonly Color CardUnplayable = new Color(0.40f, 0.40f, 0.44f, 1f);
        public static readonly Color Upgraded = new Color(0.55f, 0.85f, 0.60f, 1f);

        // Actors
        public static readonly Color Lampwright = new Color(1f, 0.74f, 0.36f, 1f);

        // Card metrics, shared by the generated prefab and any runtime layout
        public const float CardWidth = 200f;
        public const float CardHeight = 280f;
        public const float CardSpacing = 16f;
    }
}
